# **REGO MONTOR**

# **I. Data Understanding**

## ***A. Penjabaran Studi Kasus***

bla bla bla "Tolong Prediksi Harga Mobil" bla bla bla

## ***B. Import Dataset***

In [111]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [112]:
dataset = pd.read_csv("CarPrice_Assignment.csv")
dataset

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

# **II. Data Preparation**

## ***A. Exploratory Data Analysis***

### 1. Inspeksi Daftar Variabel

In [113]:
dataset.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

karena pengertian dari setiap kolom sudah ada, kita tinggal memhami jenis data di setiap kolom itu apa

Kategorik Nominal: `CarName`, `doornumber`, `carbody`, `drivewheel`, `enginelocation`

Kategorik Ordinal: `symboling`, `fueltype`, `aspiration`, `enginetype`

Numerik Continue: `wheelbase`, `carlength`, `carwidth`, `carheight`, `curbweight`, `fuelsystem`, `boreratio`, `stroke`, `peakrpm`, `citympg`, `highwaympg`

Numerik Diskrit: `cylindernumber`, `enginesize`, `compressionratio`, `horsepower`

In [114]:
fitur_continu = ['wheelbase', 'carlength', 'carwidth', 'carheight', 'curbweight', 'boreratio', 'stroke', 'peakrpm', 'citympg', 'highwaympg']
fitur_diskrit = ['cylindernumber', 'enginesize', 'compressionratio', 'horsepower']
fitur_nominal = ['CarName', 'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'fuelsystem']
fitur_ordinal = ['symboling', 'fueltype', 'aspiration', 'enginetype']

### 2. Inspeksi Informasi Ringkas

In [115]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

### 3. Inspeksi Statistik Deskriptif

In [116]:
dataset.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [117]:
dataset[fitur_continu].var()

wheelbase         36.261782
carlength        152.208688
carwidth           4.601900
carheight          5.970800
curbweight    271107.874319
boreratio          0.073356
stroke             0.098343
peakrpm       227515.303682
citympg           42.799617
highwaympg        47.423099
dtype: float64

In [118]:
dataset[['enginesize', 'compressionratio', 'horsepower']].var()

enginesize          1734.113917
compressionratio      15.777104
horsepower          1563.741129
dtype: float64

In [119]:
def data_range(dataset, col):
    for cols in col:
        Q1 = dataset[cols].quantile(0.25)
        Q3 = dataset[cols].quantile(0.75)

        IQR = Q3 - Q1

        print(f"Rentang Data Kolom: {cols}")
        print(f"Q1: {Q1}")
        print(f"Q3: {Q3}")
        print(f"IQR: {IQR}\n")

data_range(dataset, fitur_continu)

Rentang Data Kolom: wheelbase
Q1: 94.5
Q3: 102.4
IQR: 7.900000000000006

Rentang Data Kolom: carlength
Q1: 166.3
Q3: 183.1
IQR: 16.799999999999983

Rentang Data Kolom: carwidth
Q1: 64.1
Q3: 66.9
IQR: 2.8000000000000114

Rentang Data Kolom: carheight
Q1: 52.0
Q3: 55.5
IQR: 3.5

Rentang Data Kolom: curbweight
Q1: 2145.0
Q3: 2935.0
IQR: 790.0

Rentang Data Kolom: boreratio
Q1: 3.15
Q3: 3.58
IQR: 0.43000000000000016

Rentang Data Kolom: stroke
Q1: 3.11
Q3: 3.41
IQR: 0.30000000000000027

Rentang Data Kolom: peakrpm
Q1: 4800.0
Q3: 5500.0
IQR: 700.0

Rentang Data Kolom: citympg
Q1: 19.0
Q3: 30.0
IQR: 11.0

Rentang Data Kolom: highwaympg
Q1: 25.0
Q3: 34.0
IQR: 9.0

In [120]:
data_range(dataset, ['enginesize', 'compressionratio', 'horsepower'])

Rentang Data Kolom: enginesize
Q1: 97.0
Q3: 141.0
IQR: 44.0

Rentang Data Kolom: compressionratio
Q1: 8.6
Q3: 9.4
IQR: 0.8000000000000007

Rentang Data Kolom: horsepower
Q1: 70.0
Q3: 116.0
IQR: 46.0

### 4. Inspeksi Data NaN

In [121]:
dataset.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

### 5. Inspeksi Data Duplicated

In [122]:
dataset.duplicated().sum()

np.int64(0)

### 6. Univariate Analysis

#### *a. Inspeksi Distribusi Kelas Target*

karena target masih numerik continue, kita tidak bisa mengecek distribusi kelasnya

#### *b. Inspeksi Distribusi Kelas Fitur*

In [123]:
categorical_feature = ['CarName', 'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'fuelsystem', 'symboling', 'fueltype', 'aspiration', 'enginetype', 'symboling', 'fueltype', 'aspiration', 'enginetype']

def value_check(dataset, feature):
    for col in dataset[feature]:
        print("=" * 40)
        print(f'Value Counts for: {col}')
        print("=" * 40)
        print(dataset[col].value_counts(dropna=False))
        print("\n")

value_check(dataset, categorical_feature)

========================================
Value Counts for: CarName
========================================
CarName
peugeot 504                 6
toyota corolla              6
toyota corona               6
subaru dl                   4
mitsubishi outlander        3
                           ..
volkswagen super beetle     1
volkswagen rabbit custom    1
volvo 245                   1
volvo diesel                1
volvo 246                   1
Name: count, Length: 147, dtype: int64


========================================
Value Counts for: doornumber
========================================
doornumber
four    115
two      90
Name: count, dtype: int64


========================================
Value Counts for: carbody
========================================
carbody
sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: count, dtype: int64


========================================
Value Counts for: drivewheel
========================================
drivewheel
fwd    120
rwd     76
4wd      9
Name: count, dtype: int64


========================================
Value Counts for: enginelocation
========================================
enginelocation
front    202
rear       3
Name: count, dtype: int64


========================================
Value Counts for: fuelsystem
========================================
fuelsystem
mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: count, dtype: int64


========================================
Value Counts for: symboling
========================================
symboling
 0    67
 1    54
 2    32
 3    27
-1    22
-2     3
Name: count, dtype: int64


========================================
Value Counts for: fueltype
========================================
fueltype
gas       185
diesel     20
Name: count, dtype: int64


========================================
Value Counts for: aspiration
========================================
aspiration
std      168
turbo     37
Name: count, dtype: int64


========================================
Value Counts for: enginetype
========================================
enginetype
ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: count, dtype: int64


========================================
Value Counts for: symboling
========================================
symboling
 0    67
 1    54
 2    32
 3    27
-1    22
-2     3
Name: count, dtype: int64


========================================
Value Counts for: fueltype
========================================
fueltype
gas       185
diesel     20
Name: count, dtype: int64


========================================
Value Counts for: aspiration
========================================
aspiration
std      168
turbo     37
Name: count, dtype: int64


========================================
Value Counts for: enginetype
========================================
enginetype
ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: count, dtype: int64

### 7. Dataset Sementara

#### a. Dataset Sementara

In [124]:
dataset_copy = dataset.copy()

#### b. Encode Target

In [125]:
dataset_copy['price'] = dataset_copy['price'].apply(lambda x: "expensive" if x >= 16503 else ("affordable" if x >= 10295 else "cheap"))

In [126]:
dataset_copy['price'].value_counts()

price
cheap         102
expensive      52
affordable     51
Name: count, dtype: int64

#### c. Ekstraksi CarName

In [ ]:
keywords = ['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda', 'isuzu', 'jaguar', 'maxda' , 'mazda', 'buick', 'mitsubishi', 'nissan', 'peugeot', 'plymouth' ]

In [128]:
dataset_copy['CarName'].value_counts()

CarName
peugeot 504                 6
toyota corolla              6
toyota corona               6
subaru dl                   4
mitsubishi outlander        3
                           ..
volkswagen super beetle     1
volkswagen rabbit custom    1
volvo 245                   1
volvo diesel                1
volvo 246                   1
Name: count, Length: 147, dtype: int64

#### d. Encode Fitur Nominal

In [129]:
def nominal_encode(dataset, col):
    for cols in col:
        dataset[cols] = pd.factorize(dataset[cols])[0]
    return dataset

dataset_copy = nominal_encode(dataset, fitur_nominal)

dataset_copy

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,0,gas,std,0,0,0,0,88.6,...,130,0,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,1,gas,std,0,0,0,0,88.6,...,130,0,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,2,gas,std,0,1,0,0,94.5,...,152,0,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,3,gas,std,1,2,1,0,99.8,...,109,0,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,4,gas,std,1,2,2,0,99.4,...,136,0,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,140,gas,std,1,2,0,0,109.1,...,141,0,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,141,gas,turbo,1,2,0,0,109.1,...,141,0,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,142,gas,std,1,2,0,0,109.1,...,173,0,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,146,diesel,turbo,1,2,0,0,109.1,...,145,6,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,144,gas,turbo,1,2,0,0,109.1,...,141,0,3.78,3.15,9.5,114,5400,19,25,22625.0